---
- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user | default('user1') }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes
    createhome: yes
    password: "{{ admin_user_password | string | password_hash('sha512') }}"

