- name: Install software-properties-common
  become: yes
  apt:
    name: software-properties-common
    state: present

- name: Add PHP PPA repository
  become: yes
  apt_repository:
    repo: ppa:ondrej/php

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install PHP and extensions on Debian-based systems
  apt:
    name: 
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-pgsql
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php-json
      - php{{ php_version }}-curl
      - php{{ php_version }}-xml
      - php{{ php_version }}-dom
      - php{{ php_version }}-curl
      - php{{ php_version }}-zip
      - php{{ php_version }}-gd
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-intl
      - php{{ php_version }}-soap
      - php{{ php_version }}-xmlrpc
      - php{{ php_version }}-ssh2
    state: present
  when: ansible_os_family == "Debian"
  
- name: Ensure PHP-FPM is running and enabled on Debian-based systems
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
  
  
# - name: Ensure sqlite3 extension is enabled in php.ini
#   become: yes
#   lineinfile:
#     path: "/etc/php/{{ php_version }}/cli/php.ini"
#     regexp: "^;extension=sqlite3"
#     line: "extension=sqlite3"
#     state: present
#   when: ansible_os_family == "Debian"
#
# - name: Ensure pdo_sqlite extension is enabled in php.ini
#   become: yes
#   lineinfile:
#     path: "/etc/php/{{ php_version }}/cli/php.ini"
#     regexp: "^;?extension=pdo_sqlite"
#     line: "extension=pdo_sqlite"
#     state: present
#   when: ansible_os_family == "Debian"
#
# - name: Ensure sqlite3 extension is enabled in php-fpm.ini
#   become: yes
#   lineinfile:
#     path: "/etc/php/{{ php_version }}/fpm/php.ini"
#     regexp: "^;extension=sqlite3"
#     line: "extension=sqlite3"
#     state: present
#   when: ansible_os_family == "Debian"
#
# - name: Ensure pdo_sqlite extension is enabled in php-fpm.ini
#   become: yes
#   lineinfile:
#     path: "/etc/php/{{ php_version }}/fpm/php.ini"
#     regexp: "^;?extension=pdo_sqlite"
#     line: "extension=pdo_sqlite"
#     state: present
#   when: ansible_os_family == "Debian"


- name: Restart PHP-FPM to apply changes
  become: yes
  service:
    name: php{{ php_version }}-fpm
    state: restarted
  when: ansible_os_family == "Debian"

